application: wwb
version: 2
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon

- url: /canvas.html
  static_files: static/canvas.html
  upload: static/canvas.html
  
- url: /rpc_relay.html
  static_files: static/rpc_relay.html
  upload: static/rpc_relay.html
  
#- url: /static
#  static_dir: static
  
#- url: /css
#  static_dir: templates/static

- url: /.*
  script: main.py

